[project]
name = "sport-fittings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.3",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]
